### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stderr' of undefined

### ISSUE THREAD

**Issue by 2cancan** [BuZZ-dEE/open-file-in#1]
[Enter steps to reproduce below:]
1. ...experimenting   with an unremakable file  
2. ...tried to use  open-file-in package...
   3.....   error   thrown

**Atom Version**: 1.0.7
**System**: Microsoft Windows 8.1
**Thrown From**: [open-file-in](https://github.com/BuZZ-dEE/open-file-in) package, v1.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'stderr' of undefined

```
At C:\Users\johna_000\.atom\packages\open-file-in\lib\open-in-app-view.coffee:54

TypeError: Cannot read property 'stderr' of undefined
  at OpenInAppView.module.exports.OpenInAppView.confirmed (C:\Users\johna_000\.atom\packages\open-file-in\lib\open-in-app-view.coffee:54:9)
  at OpenInAppView.confirmed (C:\Users\johna_000\.atom\packages\open-file-in\lib\open-in-app-view.coffee:1:1)
  at OpenInAppView.module.exports.SelectListView.confirmSelection (C:\ProgramData\johna_000\atom\app-1.0.7\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-li.<anonymous> (C:\ProgramData\johna_000\atom\app-1.0.7\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (C:\ProgramData\johna_000\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (C:\ProgramData\johna_000\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
     -4:19.7.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -3:59.5.0 minimap:toggle (div.settings-view.pane-item)
     -1:11.6.0 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
     -1:00.4.0 styleguide:show (atom-text-editor.editor.is-focused)
  2x -0:26.5.0 open-in:toggle (div.styleguide.pane-item.native-key-bindings.padded)
```
### Config

``` json
{
  "core": {
    "followSymlinks": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
bottom-dock, v0.3.2
foundation5-snippets, v0.2.2
gulp-manager, v0.2.6
gulp-snippets, v0.6.1
linkify, v0.11.0
minimap, v4.13.1
open-file-in, v1.1.0
pigments, v0.11.0
source-preview-jade, v0.1.1

# Dev
No dev packages
```

**Comment by BuZZ-dEE** [comment]
I don't have Microsoft Windows, so it would be great if you could fix it and make a pull request. Is that possible?

**Comment by BuZZ-dEE** [comment]
You could try to define your application in the settings using the complete path e.g.:

`C:\programs\program.exe`
